name: novaos
description: NovaOS Heterogeneous Multi-GPU Gaming AI and Hardened OS
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    install:
      # Drivers y Vulkan Multi-GPU (AMD + NVIDIA)
      - mesa-vulkan-drivers
      - vulkan-tools
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      
      # Blindaje Anti-Hacker y Ciberseguridad
      - firewalld
      - clamav
      - clamd
      - clamav-update
      - bubblewrap
      - fail2ban
      
      # Compatibilidad Windows (.exe) y Juegos
      - wine
      - winetricks
      - lutris
      - steam
      
      # Agentes IA y herramientas
      - git
      - curl
      - python3-pip
      - fastfetch

  - type: default-flatpaks
    install:
      - com.valvesoftware.Steam
      - com.heroicgameslauncher.hgl
      - com.discordapp.Discord
      - org.mozilla.firefox
