name: Build NovaOS ISO
on:
  workflow_dispatch:

jobs:
  blue-build:
    name: Build and Package NovaOS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build NovaOS Image
        uses: blue-build/github-action@v1.8.0
        with:
          recipe: recipe.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
